[project]
name = "nuchad"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Joe Hakim", email = "joe@ketryx.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
nuchad = "nuchad:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
